// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = {
  docSidebar: [
    {
      type: 'category',
      label: 'Architecture Decision Records',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'ADRs',
        },
      ],
    },
    {
      type: 'category',
      label: 'Executable Reference Impl.',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'ERIs',
        },
      ],
    },
    {
      type: 'category',
      label: 'Design Patterns',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Patterns',
        },
      ],
    },
  ],
};
